import type { TestPlan, RequestSpec } from "../types.js";

function sanitizeId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function jsStringLiteral(s: string): string {
  return JSON.stringify(s);
}

function buildOptions(plan: TestPlan): string {
  const { loadProfile, thresholds } = plan;

  let loadBlock: string;
  if (loadProfile.type === "ramping") {
    if (!loadProfile.stages || loadProfile.stages.length === 0) {
      throw new Error("loadProfile.type is 'ramping' but no stages were provided.");
    }
    loadBlock = `stages: ${JSON.stringify(loadProfile.stages, null, 2)},`;
  } else {
    const vus = loadProfile.vus ?? 5;
    const duration = loadProfile.duration ?? "30s";
    loadBlock = `vus: ${vus},\n  duration: ${jsStringLiteral(duration)},`;
  }

  const thresholdLines: string[] = [];
  if (thresholds?.p95Ms !== undefined) {
    thresholdLines.push(`    http_req_duration: ['p(95)<${thresholds.p95Ms}'],`);
  }
  if (thresholds?.errorRatePct !== undefined) {
    thresholdLines.push(`    http_req_failed: ['rate<${thresholds.errorRatePct / 100}'],`);
  }
  const thresholdsBlock =
    thresholdLines.length > 0 ? `thresholds: {\n${thresholdLines.join("\n")}\n  },` : "";

  // p(99) isn't in k6's default summary trend stats; request it explicitly so the parser can rely on it.
  const summaryTrendStats = `summaryTrendStats: ['avg', 'min', 'med', 'max', 'p(90)', 'p(95)', 'p(99)'],`;

  return `export const options = {\n  ${loadBlock}\n  ${summaryTrendStats}\n  ${thresholdsBlock}\n};`;
}

function buildRequestCall(req: RequestSpec): string {
  const id = sanitizeId(req.name);
  const hasBody = req.body !== undefined;
  const bodyExpr = hasBody
    ? typeof req.body === "string"
      ? jsStringLiteral(req.body)
      : `JSON.stringify(${JSON.stringify(req.body)})`
    : "null";

  const headers = { ...(req.headers ?? {}) };
  if (hasBody && typeof req.body !== "string" && !Object.keys(headers).some((h) => h.toLowerCase() === "content-type")) {
    headers["Content-Type"] = "application/json";
  }

  const expectStatus = req.expectStatus;
  const checkStatus = expectStatus !== undefined ? `res.status === ${expectStatus}` : `res.status < 400`;
  const checks: string[] = [`[\`${req.name}: status ok\`]: (res) => ${checkStatus}`];
  if (req.maxDurationMs !== undefined) {
    checks.push(`[\`${req.name}: under ${req.maxDurationMs}ms\`]: (res) => res.timings.duration < ${req.maxDurationMs}`);
  }

  return `
  {
    weight: ${req.weight},
    run: function () {
      const res = http.request(${jsStringLiteral(req.method)}, \`\${BASE_URL}${req.path}\`, ${bodyExpr}, {
        headers: ${JSON.stringify(headers)},
        tags: { name: ${jsStringLiteral(req.name)} },
      });
      const ok = check(res, {
        ${checks.join(",\n        ")}
      }, { name: ${jsStringLiteral(req.name)} });
      trend_${id}.add(res.timings.duration);
      failRate_${id}.add(!ok);
    },
  }`;
}

/**
 * Turns a structured TestPlan into a runnable, self-contained k6 script.
 * Deterministic templating (no LLM call here) so generated scripts are reproducible
 * and reviewable before they're ever run.
 */
export function generateK6Script(plan: TestPlan): string {
  const metricDecls = plan.requests
    .map((r) => {
      const id = sanitizeId(r.name);
      return `const trend_${id} = new Trend(${jsStringLiteral(`duration_${id}`)}, true);\nconst failRate_${id} = new Rate(${jsStringLiteral(`failed_${id}`)});`;
    })
    .join("\n");

  const mixEntries = plan.requests.map(buildRequestCall).join(",\n");

  return `// Auto-generated by perf-agent. Review before running against anything but a sandbox.
import http from 'k6/http';
import { check, sleep } from 'k6';
import { Trend, Rate } from 'k6/metrics';

${buildOptions(plan)}

const BASE_URL = ${jsStringLiteral(plan.baseUrl)};
const THINK_TIME_MS = ${plan.thinkTimeMs};

${metricDecls}

// Weighted request mix: each VU iteration picks one request according to its weight.
const mix = [${mixEntries}
];
const totalWeight = mix.reduce((sum, r) => sum + r.weight, 0);
function pickRequest() {
  let r = Math.random() * totalWeight;
  for (const entry of mix) {
    if (r < entry.weight) return entry;
    r -= entry.weight;
  }
  return mix[mix.length - 1];
}

export default function () {
  pickRequest().run();
  if (THINK_TIME_MS > 0) {
    sleep(THINK_TIME_MS / 1000);
  }
}
`;
}
